version: '3'

services:
  web:
    build: ./web
    environment:
      - HERE_JS_API_KEY
      - HOTELS_NEARBY_SERVICE_URL=http://localhost:8081
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - service
  service:
    build: ./service
    environment:
      - HERE_REST_API_KEY
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
        - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
