version: '3'

services:
  web:
    build: ./web
    environment:
      - HERE_JS_API_KEY
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - service
  service:
    build: ./service
    environment:
      - HERE_REST_API_KEY
    volumes:
      - ./service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8081:8081"
