FROM node:10-alpine AS base
WORKDIR /usr/src/app

FROM base AS dependencies  
COPY package*.json ./
RUN npm install

FROM dependencies AS build  
COPY webpack.config.js ./
COPY ./src ./src
RUN npm run build

FROM node:10-alpine AS release  
WORKDIR /usr/src/app
COPY --from=dependencies /usr/src/app/package.json ./
COPY --from=build /usr/src/app/dist ./dist
RUN npm install serve

CMD [ "npm", "run", "startprod" ]
